runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3
# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: main.app
skip_files:
- ^(.*/)?\.bak$
# [END handlers]